-- Second Catalog Products with 30% Markup
-- Generated on 2025-12-25 18:11:54

INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (1, 'Professional Leather Boxing Gloves - Competition Grade', 'professional-leather-boxing-gloves-competition', 'Premium competition-grade leather boxing gloves with advanced padding system. AIBA approved for amateur competitions.', 1235.0, 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&crop=faces&cs=tinysrgb', '["./catalog2_images/catalog2_page_003_image_003.jpeg"]', '["10oz", "12oz", "14oz", "16oz"]', '["Black", "Red", "Blue"]', 1, 25);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (1, 'Sparring Boxing Gloves - Extra Padding', 'sparring-boxing-gloves-extra-padding', 'Extra padded boxing gloves designed for safe sparring sessions. Superior hand protection with ergonomic design.', 884.0, 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&crop=faces&cs=tinysrgb', '["./catalog2_images/catalog2_page_004_image_002.jpeg"]', '["12oz", "14oz", "16oz", "18oz"]', '["Black", "White", "Red"]', 0, 35);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (2, 'Double End Speed Ball - Professional', 'double-end-speed-ball-professional', 'Professional double-end speed ball for improving accuracy and timing. Adjustable height with quality elastics.', 416.0, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&crop=faces&cs=tinysrgb', '["./catalog2_images/catalog2_page_006_image_001.jpeg"]', '["Standard"]', '["Black", "Red"]', 0, 20);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (2, 'Professional Punching Mitts', 'professional-punching-mitts', 'High-quality punching mitts for trainer-athlete drills. Curved design for optimal impact absorption.', 754.0, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&crop=faces&cs=tinysrgb', '["./catalog2_images/catalog2_page_007_image_002.jpeg"]', '["Standard"]', '["Black", "Red", "Blue"]', 1, 30);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (2, 'Muay Thai Heavy Bag - 180cm', 'muay-thai-heavy-bag-180cm', 'Extra-long Muay Thai heavy bag perfect for kick training. Durable synthetic leather with reinforced chains.', 2860.0, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&crop=faces&cs=tinysrgb', '["./catalog2_images/catalog2_page_008_image_001.jpeg"]', '["180cm"]', '["Black", "Red"]', 1, 8);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (2, 'Thai Pads - Curved Design', 'thai-pads-curved-design', 'Authentic Thai pads with curved design for kick and knee training. Professional grade with secure arm straps.', 936.0, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&crop=faces&cs=tinysrgb', '["./catalog2_images/catalog2_page_009_image_003.jpeg"]', '["Standard"]', '["Black", "Red", "Blue", "Yellow"]', 0, 22);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (3, 'Premium Muay Thai Shorts - Satin', 'premium-muay-thai-shorts-satin', 'Premium satin Muay Thai shorts with traditional Thai designs. Lightweight and comfortable for competition.', 455.0, 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400&crop=faces&cs=tinysrgb', '["./catalog2_images/catalog2_page_012_image_001.jpeg"]', '["S", "M", "L", "XL", "XXL"]', '["Red", "Blue", "Black", "White", "Gold", "Green"]', 1, 45);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (3, 'Boxing Rash Guard - Long Sleeve', 'boxing-rash-guard-long-sleeve', 'Compression rash guard for boxing and MMA training. Moisture-wicking fabric with anti-bacterial treatment.', 364.0, 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400&crop=faces&cs=tinysrgb', '["./catalog2_images/catalog2_page_014_image_002.jpeg"]', '["S", "M", "L", "XL", "XXL"]', '["Black", "White", "Blue", "Red"]', 0, 40);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (3, 'Training Shorts - Elastic Waistband', 'training-shorts-elastic-waistband', 'Comfortable training shorts with elastic waistband. Perfect for boxing, MMA, and general fitness training.', 286.0, 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400&crop=faces&cs=tinysrgb', '["./catalog2_images/catalog2_page_015_image_003.jpeg"]', '["S", "M", "L", "XL", "XXL"]', '["Black", "Gray", "Navy", "Red"]', 0, 50);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (4, 'Full Face Headgear - Competition', 'full-face-headgear-competition', 'Full face protection headgear for amateur boxing competitions. AIBA approved with clear vision design.', 1105.0, 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=400&crop=faces&cs=tinysrgb', '["./catalog2_images/catalog2_page_017_image_001.jpeg"]', '["S", "M", "L", "XL"]', '["Red", "Blue"]', 0, 15);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (4, 'Ankle Guards - Muay Thai', 'ankle-guards-muay-thai', 'Professional ankle guards for Muay Thai and kickboxing. Elastic support with reinforced padding.', 234.0, 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=400&crop=faces&cs=tinysrgb', '["./catalog2_images/catalog2_page_018_image_004.jpeg"]', '["S", "M", "L", "XL"]', '["Black", "Blue", "White"]', 0, 35);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (4, 'Professional Mouthguard - Custom Fit', 'professional-mouthguard-custom-fit', 'Boil-and-bite mouthguard for custom fit protection. Essential safety gear for sparring and competition.', 123.5, 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=400&crop=faces&cs=tinysrgb', '["./catalog2_images/catalog2_page_019_image_002.jpeg"]', '["Junior", "Senior"]', '["Clear", "Black", "Red", "Blue"]', 0, 60);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (4, 'Knee Pads - Heavy Duty', 'knee-pads-heavy-duty', 'Heavy duty knee pads for floor work and grappling. Durable construction with secure velcro straps.', 312.0, 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=400&crop=faces&cs=tinysrgb', '["./catalog2_images/catalog2_page_020_image_003.jpeg"]', '["S", "M", "L", "XL"]', '["Black", "Blue"]', 0, 25);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (2, 'Skipping Rope - Leather', 'skipping-rope-leather', 'Professional leather skipping rope with wooden handles. Perfect for boxing conditioning and cardio training.', 156.0, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&crop=faces&cs=tinysrgb', '["./catalog2_images/catalog2_page_022_image_001.jpeg"]', '["3m"]', '["Brown"]', 0, 50);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (2, 'Training Timer - Digital', 'training-timer-digital', 'Digital interval timer for boxing and MMA training. Programmable rounds with clear audio signals.', 494.0, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&crop=faces&cs=tinysrgb', '["./catalog2_images/catalog2_page_023_image_004.jpeg"]', '["Standard"]', '["Black"]', 0, 15);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (2, 'Hand Wraps - Elastic Cotton', 'hand-wraps-elastic-cotton', 'Premium elastic cotton hand wraps with thumb loop. Essential protection for training and competition.', 97.5, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&crop=faces&cs=tinysrgb', '["./catalog2_images/catalog2_page_024_image_003.jpeg"]', '["4.5m"]', '["Black", "Red", "Blue", "White", "Pink"]', 0, 100);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (3, 'Gym Bag - Professional', 'gym-bag-professional', 'Large professional gym bag with multiple compartments. Perfect for carrying all your training equipment.', 585.0, 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400&crop=faces&cs=tinysrgb', '["./catalog2_images/catalog2_page_025_image_005.jpeg"]', '["Standard"]', '["Black", "Red", "Navy"]', 0, 20);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (2, 'Water Bottle - Sports', 'water-bottle-sports', 'Professional sports water bottle with measurement markers. BPA-free with easy-squeeze design.', 110.5, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&crop=faces&cs=tinysrgb', '["./catalog2_images/catalog2_page_026_image_001.jpeg"]', '["750ml"]', '["Clear", "Black", "Blue", "Red"]', 0, 40);
