-- Kixx Fighgear Catalog Products with 30% Markup
-- Generated on 2025-12-25 18:05:24

INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (1, 'Kixx Professional Boxing Gloves - Premium Leather', 'kixx-pro-boxing-gloves-leather', 'Professional grade leather boxing gloves with superior padding and wrist support. Perfect for training and competition.', 1105.0, 'https://via.placeholder.com/400x400?text=Kixx+Professional+Boxing+Gloves+-+Premium+Leather', '["./extracted_images/page_003_image_001.jpeg"]', '["10oz", "12oz", "14oz", "16oz"]', '["Black", "Red", "Blue", "White"]', 1, 30);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (1, 'Kixx Training Boxing Gloves - Synthetic', 'kixx-training-boxing-gloves-synthetic', 'Durable synthetic boxing gloves ideal for regular training. Great value with excellent protection.', 546.0, 'https://via.placeholder.com/400x400?text=Kixx+Training+Boxing+Gloves+-+Synthetic', '["./extracted_images/page_004_image_001.jpeg"]', '["10oz", "12oz", "14oz", "16oz"]', '["Black", "Blue", "Red"]', 0, 45);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (2, 'Kixx Heavy Bag - 120lbs Professional', 'kixx-heavy-bag-120lbs', 'Professional quality heavy bag filled with high-density materials. Durable synthetic leather construction.', 2405.0, 'https://via.placeholder.com/400x400?text=Kixx+Heavy+Bag+-+120lbs+Professional', '["./extracted_images/page_009_image_001.jpeg"]', '["120lbs"]', '["Black", "Red"]', 1, 12);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (2, 'Kixx Speed Bag - Professional Grade', 'kixx-speed-bag-professional', 'High-quality speed bag for improving hand-eye coordination and boxing speed. Durable construction.', 494.0, 'https://via.placeholder.com/400x400?text=Kixx+Speed+Bag+-+Professional+Grade', '["./extracted_images/page_010_image_002.jpeg"]', '["Standard"]', '["Black", "Red"]', 0, 25);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (2, 'Kixx Focus Pads - Curved Design', 'kixx-focus-pads-curved', 'Ergonomically designed focus pads with curved surface for optimal training. High-impact absorption.', 676.0, 'https://via.placeholder.com/400x400?text=Kixx+Focus+Pads+-+Curved+Design', '["./extracted_images/page_011_image_006.jpeg"]', '["Standard"]', '["Black", "Red", "Blue"]', 0, 20);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (3, 'Kixx Muay Thai Shorts - Traditional', 'kixx-muay-thai-shorts-traditional', 'Authentic Muay Thai shorts with traditional design and lightweight fabric. Perfect for training and competition.', 364.0, 'https://via.placeholder.com/400x400?text=Kixx+Muay+Thai+Shorts+-+Traditional', '["./extracted_images/page_013_image_002.jpeg"]', '["S", "M", "L", "XL", "XXL"]', '["Red", "Blue", "Black", "White", "Green"]', 1, 50);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (3, 'Kixx Boxing T-Shirt - Performance Fabric', 'kixx-boxing-tshirt-performance', 'High-performance training t-shirt with moisture-wicking technology. Comfortable for intense training sessions.', 234.0, 'https://via.placeholder.com/400x400?text=Kixx+Boxing+T-Shirt+-+Performance+Fabric', '["./extracted_images/page_015_image_003.jpeg"]', '["S", "M", "L", "XL", "XXL"]', '["Black", "White", "Gray", "Blue"]', 0, 60);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (4, 'Kixx Headgear - Competition Grade', 'kixx-headgear-competition', 'Professional headgear with excellent protection and visibility. Lightweight design for comfort during sparring.', 845.0, 'https://via.placeholder.com/400x400?text=Kixx+Headgear+-+Competition+Grade', '["./extracted_images/page_018_image_001.jpeg"]', '["S", "M", "L", "XL"]', '["Black", "Red", "Blue", "White"]', 0, 18);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (4, 'Kixx Shin Guards - Premium Protection', 'kixx-shin-guards-premium', 'High-quality shin guards with superior protection for Muay Thai and kickboxing. Secure strapping system.', 624.0, 'https://via.placeholder.com/400x400?text=Kixx+Shin+Guards+-+Premium+Protection', '["./extracted_images/page_019_image_002.jpeg"]', '["S", "M", "L", "XL"]', '["Black", "Blue", "Red"]', 1, 22);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (2, 'Kixx Boxing Wraps - Cotton Blend', 'kixx-boxing-wraps-cotton', 'Professional boxing hand wraps made from cotton blend. Essential protection for hands and wrists.', 110.5, 'https://via.placeholder.com/400x400?text=Kixx+Boxing+Wraps+-+Cotton+Blend', '["./extracted_images/page_021_image_003.jpeg"]', '["180cm"]', '["Black", "Red", "Blue", "White"]', 0, 80);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (2, 'Kixx MMA Gloves - Open Finger', 'kixx-mma-gloves-open-finger', 'Professional MMA training gloves with open finger design. Excellent for grappling and striking.', 546.0, 'https://via.placeholder.com/400x400?text=Kixx+MMA+Gloves+-+Open+Finger', '["./extracted_images/page_023_image_001.jpeg"]', '["S", "M", "L", "XL"]', '["Black", "Red"]', 0, 35);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (2, 'Kixx Kick Shield - Heavy Duty', 'kixx-kick-shield-heavy-duty', 'Professional kick shield for training powerful kicks. Reinforced construction with comfortable grip handles.', 975.0, 'https://via.placeholder.com/400x400?text=Kixx+Kick+Shield+-+Heavy+Duty', '["./extracted_images/page_024_image_002.jpeg"]', '["Standard"]', '["Black", "Red"]', 0, 15);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (3, 'Kixx Boxing Boots - Professional', 'kixx-boxing-boots-professional', 'Professional boxing boots with ankle support and non-slip sole. Lightweight design for optimal performance.', 1196.0, 'https://via.placeholder.com/400x400?text=Kixx+Boxing+Boots+-+Professional', '["./extracted_images/page_027_image_005.jpeg"]', '["38", "39", "40", "41", "42", "43", "44", "45"]', '["Black", "White", "Red"]', 0, 25);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (4, 'Kixx Groin Guard - Competition', 'kixx-groin-guard-competition', 'Professional groin protection for sparring and competition. Comfortable fit with secure strapping.', 416.0, 'https://via.placeholder.com/400x400?text=Kixx+Groin+Guard+-+Competition', '["./extracted_images/page_030_image_005.jpeg"]', '["S", "M", "L", "XL"]', '["Black"]', 0, 30);
INSERT INTO products (category_id, name, slug, description, price, image_url, images, sizes, colors, is_featured, stock_quantity) VALUES (2, 'Kixx Training Bag Gloves', 'kixx-training-bag-gloves', 'Specialized bag gloves for heavy bag training. Extra padding and wrist support for intense sessions.', 494.0, 'https://via.placeholder.com/400x400?text=Kixx+Training+Bag+Gloves', '["./extracted_images/page_032_image_003.jpeg"]', '["S", "M", "L", "XL"]', '["Black", "Red"]', 0, 40);
